# Experiment 01 – NumPy Fundamentals

This notebook demonstrates fundamental NumPy operations including:
- Array creation
- Indexing and slicing
- Data types
- Copy vs View
- Reshaping
- Iteration
- Joining and stacking
- Pattern creation


In [6]:
import numpy as np

## 1. Array Creation and Dimensions
Understanding 0D, 1D, 2D and 3D arrays using `.ndim` and `.shape`.


In [18]:
# 0D Array
a = np.array(10)
print("0D Array:", a)
print("Shape:", a.shape, "Dimension:", a.ndim)

print("\n---------------------\n")

# 1D Array
b = np.array([1, 2, 3, 4, 5])
print("1D Array:", b)
print("Shape:", b.shape, "Dimension:", b.ndim)

print("\n---------------------\n")

# 2D Array
c = np.array([[1, 2], [3, 4]])
print("2D Array:\n", c)
print("Shape:", c.shape, "Dimension:", c.ndim)

print("\n---------------------\n")

# 3D Array
d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("3D Array:\n", d)
print("Shape:", d.shape, "Dimension:", d.ndim)


0D Array: 10
Shape: () Dimension: 0

---------------------

1D Array: [1 2 3 4 5]
Shape: (5,) Dimension: 1

---------------------

2D Array:
 [[1 2]
 [3 4]]
Shape: (2, 2) Dimension: 2

---------------------

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2) Dimension: 3


## 2. Indexing (Positive and Negative)


In [9]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Element at (1,2):", arr[1,2])
print("Last Row:", arr[-1])
print("Second last element in first row:", arr[0,-2])


Element at (1,2): 6
Last Row: [7 8 9]
Second last element in first row: 2


## 3. Slicing


In [10]:
a = np.array([1,2,3,4,5,6])

print("From index 1 to 4:", a[1:4])
print("From index 2 to end:", a[2:])
print("Step slicing:", a[::2])

print("\n2D Slicing Example")

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Second Column:", b[:,1])
print("Alternate Rows:\n", b[::2])


From index 1 to 4: [2 3 4]
From index 2 to end: [3 4 5 6]
Step slicing: [1 3 5]

2D Slicing Example
Second Column: [2 5 8]
Alternate Rows:
 [[1 2 3]
 [7 8 9]]


## 4. Data Types and Type Conversion


In [11]:
a = np.array([1,2,3,4])
print("Original dtype:", a.dtype)

b = a.astype(float)
print("Converted to float:", b.dtype)

c = np.array([1,0,3])
d = c.astype(bool)
print("Converted to boolean:", d)


Original dtype: int64
Converted to float: float64
Converted to boolean: [ True False  True]


## 5. Copy vs View
Understanding memory behavior in NumPy.


In [12]:
a = np.array([1,2,3,4,5])

# Copy
b = a.copy()
a[0] = 10
print("After modifying original (Copy):")
print("Original:", a)
print("Copy:", b)

print("\n---------------------\n")

# View
a = np.array([1,2,3,4,5])
c = a.view()
a[0] = 10
print("After modifying original (View):")
print("Original:", a)
print("View:", c)


After modifying original (Copy):
Original: [10  2  3  4  5]
Copy: [1 2 3 4 5]

---------------------

After modifying original (View):
Original: [10  2  3  4  5]
View: [10  2  3  4  5]


## 6. Reshaping Arrays


In [13]:
a = np.arange(1,13)

b = a.reshape(3,4)
print("Reshaped 3x4:\n", b)

c = a.reshape(2,2,-1)
print("\nReshaped with -1:\n", c)

# Flattening
flat = b.reshape(-1)
print("\nFlattened Array:", flat)


Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped with -1:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Iterating Arrays


In [14]:
a = np.array([[1,2,3],
              [4,5,6]])

print("Standard Iteration:")
for row in a:
    for element in row:
        print(element, end=" ")
        
print("\n\nUsing nditer:")
for element in np.nditer(a):
    print(element, end=" ")


Standard Iteration:
1 2 3 4 5 6 

Using nditer:
1 2 3 4 5 6 

## 8. Joining and Stacking Arrays


In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Concatenation:", np.concatenate((a,b)))

print("\nStacking:")
print(np.stack((a,b)))


Concatenation: [1 2 3 4 5 6]

Stacking:
[[1 2 3]
 [4 5 6]]


## 9. Pattern Creation using Slicing
Creating a checkerboard-style matrix.


In [16]:
a = np.zeros((8,8), dtype=int)

a[::2, ::2] = 1
a[1::2, 1::2] = 1

print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Conclusion

This experiment demonstrates:
- Understanding of array structures
- Efficient indexing and slicing
- Memory behavior (copy vs view)
- Reshaping techniques
- Array joining and stacking
- Logical pattern creation using slicing
